### ISSUE TITLE
Getting an error caused by displaying tps

### ISSUE THREAD

**Issue by Synkstar** [PiggyPiglet/TPS#1]
[00:58:08 WARN]: [Scoreboard-revision] Plugin Scoreboard-revision vR3 1.3.1 RELEASE generated an exception while executing task 90
java.lang.NoClassDefFoundError: de/Herbystar/TTA/TTA_Methods
at me.piggypiglet.tps.TPS.onPlaceholderRequest(TPS.java:28) ~[?:?]
at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:377) ~[?:?]
at rien.bijl.Scoreboard.r.board.ScoreboardHolder.update(ScoreboardHolder.java:48) ~[?:?]
at rien.bijl.Scoreboard.r.board.App.run(App.java:96) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-551]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-551]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-551]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
[00:58:08 WARN]: [Scoreboard-revision] Plugin Scoreboard-revision vR3 1.3.1 RELEASE generated an exception while executing task 90
java.lang.NoClassDefFoundError: de/Herbystar/TTA/TTA_Methods
at me.piggypiglet.tps.TPS.onPlaceholderRequest(TPS.java:28) ~[?:?]
at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:377) ~[?:?]
at rien.bijl.Scoreboard.r.board.ScoreboardHolder.update(ScoreboardHolder.java:48) ~[?:?]
at rien.bijl.Scoreboard.r.board.App.run(App.java:96) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-551]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-551]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-551]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
[00:58:08 WARN]: [Scoreboard-revision] Plugin Scoreboard-revision vR3 1.3.1 RELEASE generated an exception while executing task 90
java.lang.NoClassDefFoundError: de/Herbystar/TTA/TTA_Methods
at me.piggypiglet.tps.TPS.onPlaceholderRequest(TPS.java:28) ~[?:?]
at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:377) ~[?:?]
at rien.bijl.Scoreboard.r.board.ScoreboardHolder.update(ScoreboardHolder.java:48) ~[?:?]
at rien.bijl.Scoreboard.r.board.App.run(App.java:96) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-551]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-551]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-551]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]

**Comment by PiggyPiglet** [comment]
you should of contacted me by discord, do you have tta installed?

**Comment by Synkstar** [comment]
Nvm I was using an old broken version of tta that didnt load. Therefore causing your extension to not work
